const anniversaires = [
    { type: "birth", name: "Aaron Leib Milgram", greg_date: "14/10/2024", heb_cal: "12 Tishrei 5785", notes: "", target: "papa, joel" },
    { type: "birth", name: "Aaron Zvi", greg_date: "3/5/2016", heb_cal: "25 Nisan 5776", notes: "Chez Rah’el et Simh'a", target: "papa, joel" },
    { type: "birth", name: "Abraham Minkowski", greg_date: "7/4/1892", heb_cal: "10 Nisan 5652", notes: "", target: "papa, joel" },
    { type: "birth", name: "Abram Albert Mendilevitch", greg_date: "26/12/1908", heb_cal: "2 Tevet 5669", notes: "", target: "papa, joel" },
    { type: "birth", name: "Abram Berek Grosberg", greg_date: "17/2/1875", heb_cal: "12 Adar I 5635", notes: "", target: "papa, joel" },
    { type: "birth", name: "Adam Chalom Nessim Kharoubi", greg_date: "18/8/2004", heb_cal: "1 Elul 5764", notes: "", target: "papa, joel" },
    { type: "birth", name: "Adassa Levy", greg_date: "26/10/2021", heb_cal: "20 Cheshvan 5782", notes: "", target: "papa, joel" },
    { type: "birth", name: "Adinah Myriam", greg_date: "9/5/1997", heb_cal: "2 Iyyar 5757", notes: "", target: "papa, joel" },
    { type: "birth", name: "Aharon David", greg_date: "31/5/1988", heb_cal: "15 Sivan 5748", notes: "", target: "papa, joel" },
    { type: "birth", name: "Akiva Dov", greg_date: "7/8/2012", heb_cal: "19 Av 5772", notes: "Chez Rah’el et Simh'a", target: "papa, joel" },
    { type: "birth", name: "Alain I Claude Majerowicz", greg_date: "22/3/1948", heb_cal: "11 Adar II 5708", notes: "", target: "papa, joel" },
    { type: "birth", name: "Alain II Henri Minkowski", greg_date: "17/3/1956", heb_cal: "5 Nisan 5716", notes: "", target: "papa, joel" },
    { type: "birth", name: "Alain Sitri un de mes trois avocats", greg_date: "27/1/1947", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Albert EINSTEIN", greg_date: "14/3/1879", heb_cal: "19 Adar 5639", notes: "", target: "papa" },
    { type: "birth", name: "anne chabrol gardienne/compagnie de maman", greg_date: "19/2/1953", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Anne Sophie Penica/Milgram", greg_date: "26/12/1969", heb_cal: "17 Tevet 5730", notes: "", target: "papa" },
    { type: "birth", name: "Annie Henriette Francoise Seignol", greg_date: "28/4/1945", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Annie Minkowski/Neuhof", greg_date: "29/2/1952", heb_cal: "3 Adar 5712", notes: "", target: "papa, joel" },
    { type: "birth", name: "Arel Milgram", greg_date: "6/8/2024", heb_cal: "2 Av 5784", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ariel Milgrom", greg_date: "8/12/2021", heb_cal: "4 Tevet 5782", notes: "", target: "papa, joel" },
    { type: "birth", name: "Arlette Léa Chiche", greg_date: "16/6/1951", heb_cal: "12 Sivan 5711", notes: "", target: "papa, joel" },
    { type: "birth", name: "Arthur Milgram", greg_date: "30/7/1995", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Avidan Yosseph", greg_date: "26/10/1985", heb_cal: "11 Cheshvan 5746", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ayala Rah'el Milgrom", greg_date: "23/8/2018", heb_cal: "12 Elul 5778", notes: "Chez Avidan et Noah", target: "papa, joel" },
    { type: "birth", name: "Ayéleth BatZion (Hanna/Yossef)", greg_date: "22/8/2019", heb_cal: "21 Av 5779", notes: "Chez Hanna et Yossef", target: "papa, joel" },
    { type: "birth", name: "Balthazar Isaac Alfred Albaric", greg_date: "11/3/1999", heb_cal: "23 Adar 5759", notes: "", target: "papa, joel" },
    { type: "birth", name: "Bastien Jean Joseph Bourg", greg_date: "20/4/1986", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Batia Milgrom", greg_date: "28/6/2016", heb_cal: "22 Sivan 5776", notes: "Chez Yéhouda/Braha", target: "papa, joel" },
    { type: "birth", name: "Batia Tova", greg_date: "20/5/1998", heb_cal: "24 Iyyar 5758", notes: "", target: "papa, joel" },
    { type: "birth", name: "Bella Mendilevici", greg_date: "28/12/1920", heb_cal: "17 Tevet 5681", notes: "", target: "papa, joel" },
    { type: "birth", name: "Benyamin", greg_date: "29/3/2014", heb_cal: "27 Adar II 5774", notes: "Chez Rah’el et Simh'a", target: "papa, joel" },
    { type: "birth", name: "Benyamin Shimon Milgrom", greg_date: "2/6/2024", heb_cal: "25 Iyyar 5784", notes: "", target: "papa, joel" },
    { type: "birth", name: "Berthe Brandla Billy Minkowska", greg_date: "1/9/1917", heb_cal: "14 Elul 5677", notes: "", target: "papa, joel" },
    { type: "birth", name: "Berthe Olivier Kittler", greg_date: "6/6/1924", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Berthe Rose Assa", greg_date: "19/10/1911", heb_cal: "27 Tishrei 5672", notes: "", target: "papa, joel" },
    { type: "birth", name: "Berthe Victoire Assa/Gregoire", greg_date: "4/6/1919", heb_cal: "6 Sivan 5679", notes: "", target: "papa, joel" },
    { type: "birth", name: "Berthe Zelda Milgram", greg_date: "10/2/1908", heb_cal: "8 Adar I 5668", notes: "Tante assassinée à AUSCHWITZ", target: "papa, joel" },
    { type: "birth", name: "Boris Todorovitch", greg_date: "1/4/1951", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Bruno Matitia", greg_date: "18/8/1971", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Shmouel ", greg_date: "31/5/2012", heb_cal: "10 Sivan 5772", notes: "", target: "papa, joel" },
    { type: "birth", name: "Clara Eden", greg_date: "19/12/1997", heb_cal: "20 Kislev 5758", notes: "", target: "papa, joel" },
    { type: "birth", name: "Clara Haia Mendilevitch", greg_date: "16/5/2002", heb_cal: "5 Sivan 5762", notes: "", target: "papa, joel" },
    { type: "birth", name: "Clément Pierre Paul Bourg", greg_date: "14/12/1988", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Cyrille Elie Paul", greg_date: "1/11/1969", heb_cal: "20 Cheshvan 5730", notes: "", target: "papa, joel" },
    { type: "birth", name: "Daniel Milgram", greg_date: "17/4/1942", heb_cal: "30 Nisan 5702", notes: "", target: "papa, joel" },
    { type: "birth", name: "Daniel Nounou Tchenio", greg_date: "27/10/1970", heb_cal: "27 Tishrei 5731", notes: "", target: "papa" },
    { type: "birth", name: "Danièle Fahri", greg_date: "10/5/1959", heb_cal: "2 Iyyar 5719", notes: "", target: "papa" },
    { type: "birth", name: "David Azulay", greg_date: "9/7/1971", heb_cal: "16 Tamuz 5731", notes: "", target: "papa" },
    { type: "birth", name: "David Fichman", greg_date: "15/6/1788", heb_cal: "10 Sivan 5548", notes: "", target: "papa, joel" },
    { type: "birth", name: "Eleazar Lazare Assa", greg_date: "16/3/1921", heb_cal: "6 Adar II 5681", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elianne Sultana Chiche", greg_date: "11/3/1947", heb_cal: "19 Adar 5707", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elias Joyeux", greg_date: "25/10/2006", heb_cal: "3 Cheshvan 5767", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elie Joseph Nanou Simon Kharoubi", greg_date: "24/7/2006", heb_cal: "28 Tamuz 5766", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elisheva (Efraïm/Léa)", greg_date: "2/8/2019", heb_cal: "1 Av 5779", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elisheva (Yéhouda/Braha)", greg_date: "5/10/2018", heb_cal: "26 Tishrei 5779", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elisheva Malka", greg_date: "25/1/2022", heb_cal: "23 Sh'vat 5782", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ella Loubet", greg_date: "18/5/2005", heb_cal: "9 Iyyar 5765", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elsa Ilana Levy Albaric", greg_date: "15/9/1971", heb_cal: "25 Elul 5731", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elsa Seignol", greg_date: "14/12/1986", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Elsa Sussman, Fille De Paul", greg_date: "14/2/1990", heb_cal: "19 Sh'vat 5750", notes: "", target: "papa" },
    { type: "birth", name: "Ephraïm", greg_date: "27/7/1992", heb_cal: "26 Tamuz 5752", notes: "", target: "papa, joel" },
    { type: "birth", name: "Esther Brouriah", greg_date: "10/5/2001", heb_cal: "17 Iyyar 5761", notes: "", target: "papa, joel" },
    { type: "birth", name: "Esther Ety Minkowska", greg_date: "29/9/1918", heb_cal: "23 Tishrei 5679", notes: "", target: "papa, joel" },
    { type: "birth", name: "État d'ISRAEL", greg_date: "15/5/1948", heb_cal: "6 Iyyar 5708", notes: "", target: "papa" },
    { type: "birth", name: "Ethan Korsia", greg_date: "14/2/2002", heb_cal: "2 Adar 5762", notes: "", target: "papa" },
    { type: "birth", name: "Ety Esther", greg_date: "29/9/1918", heb_cal: "23 Tishrei 5679", notes: "", target: "papa, joel" },
    { type: "birth", name: "Éva", greg_date: "6/11/1976", heb_cal: "13 Cheshvan 5737", notes: "", target: "papa, joel" },
    { type: "birth", name: "Éve(lyne) Mendilevitch-Levy", greg_date: "13/9/1944", heb_cal: "25 Elul 5704", notes: "", target: "papa, joel" },
    { type: "birth", name: "Évelyne Albertine Martin", greg_date: "5/5/1944", heb_cal: "12 Iyyar 5704", notes: "", target: "papa, joel" },
    { type: "birth", name: "Fabienne Jaouën", greg_date: "2/8/1964", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Fabienne Wachman", greg_date: "1/7/1963", heb_cal: "9 Tamuz 5723", notes: "", target: "papa, joel" },
    { type: "birth", name: "Fajga Szajndla Grosbard", greg_date: "23/7/1872", heb_cal: "17 Tamuz 5632", notes: "", target: "papa, joel" },
    { type: "birth", name: "Francis Noé Assa", greg_date: "21/2/1914", heb_cal: "25 Sh'vat 5674", notes: "", target: "papa, joel" },
    { type: "birth", name: "françois pierre claude bourg", greg_date: "22/4/1953", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Frédéric David Milgram", greg_date: "2/12/1963", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Gabriel Milgram", greg_date: "6/9/1995", heb_cal: "11 Elul 5755", notes: "", target: "papa, joel" },
    { type: "birth", name: "Galia Evelyne Wachman", greg_date: "3/10/1956", heb_cal: "28 Tishrei 5717", notes: "", target: "papa, joel" },
    { type: "birth", name: "Gérard Sinden", greg_date: "18/7/1945", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Gilbert Robert Mizrahi", greg_date: "27/2/2019", heb_cal: "22 Adar I 5779", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ginette Lyliane", greg_date: "29/1/1946", heb_cal: "27 Sh'vat 5706", notes: "", target: "papa, joel" },
    { type: "birth", name: "Golda Majerowicz", greg_date: "16/12/2006", heb_cal: "25 Kislev 5767", notes: "", target: "papa, joel" },
    { type: "birth", name: "GUZ gaétano ubaldo zanardi", greg_date: "16/2/1920", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Hanania (Efraïm/Léa)", greg_date: "2/6/2018", heb_cal: "19 Sivan 5778", notes: "", target: "papa, joel" },
    { type: "birth", name: "Hanna Aouva Valershteiner", greg_date: "27/4/2023", heb_cal: "6 Iyyar 5783", notes: "", target: "papa, joel" },
    { type: "birth", name: "Hanna", greg_date: "15/6/1788", heb_cal: "10 Sivan 5548", notes: "", target: "papa, joel" },
    { type: "birth", name: "Hannah Nitzah", greg_date: "13/12/1993", heb_cal: "29 Kislev 5754", notes: "", target: "papa, joel" },
    { type: "birth", name: "Harry Schartenberg", greg_date: "22/7/1908", heb_cal: "23 Tamuz 5668", notes: "", target: "papa, joel" },
    { type: "birth", name: "Hélène Jeanne Claude Milgram Bourg", greg_date: "18/9/1957", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Hélène Minkowski Cerignano", greg_date: "23/7/1933", heb_cal: "29 Tamuz 5693", notes: "", target: "papa, joel" },
    { type: "birth", name: "Henri Michel Majerowicz", greg_date: "6/8/1918", heb_cal: "28 Av 5678", notes: "", target: "papa, joel" },
    { type: "birth", name: "Henri Willy S,", greg_date: "2/6/1912", heb_cal: "17 Sivan 5672", notes: "", target: "papa" },
    { type: "birth", name: "Hermann Minkowski", greg_date: "2/3/1943", heb_cal: "25 Adar I 5703", notes: "", target: "papa, joel" },
    { type: "birth", name: "Houmalè Grossberg/Milgram", greg_date: "16/8/1880", heb_cal: "9 Elul 5640", notes: "", target: "papa, joel" },
    { type: "birth", name: "Hugo Giovanni Daniel Falivène", greg_date: "1/5/2000", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ilana Golda Violette", greg_date: "1/3/2000", heb_cal: "24 Adar I 5760", notes: "", target: "papa, joel" },
    { type: "birth", name: "Illel Zwi", greg_date: "4/4/1996", heb_cal: "15 Nisan 5756", notes: "PESSAH TAL 1°jour", target: "papa, joel" },
    { type: "birth", name: "Isaac Abramov Mendilevitch", greg_date: "5/7/1874", heb_cal: "20 Tamuz 5634", notes: "", target: "papa, joel" },
    { type: "birth", name: "Isaac Levy", greg_date: "19/3/1988", heb_cal: "1 Nisan 5748", notes: "", target: "papa, joel" },
    { type: "birth", name: "Isidor Itzhak Neuhof", greg_date: "23/8/1951", heb_cal: "21 Av 5711", notes: "", target: "papa, joel" },
    { type: "birth", name: "Israel (Yéhouda/Braha)", greg_date: "20/1/2020", heb_cal: "23 Tevet 5780", notes: "", target: "papa, joel" },
    { type: "birth", name: "Issachar Haim", greg_date: "8/7/2021", heb_cal: "28 Tamuz 5781", notes: "", target: "papa, joel" },
    { type: "birth", name: "Itamar (Avidan/Noah)", greg_date: "29/10/2015", heb_cal: "16 Cheshvan 5776", notes: "", target: "papa, joel" },
    { type: "birth", name: "Itsik Peretz", greg_date: "29/3/1957", heb_cal: "26 Adar II 5717", notes: "", target: "papa, joel" },
    { type: "birth", name: "Izrael Srul Rozenbaum Rajzenbaum", greg_date: "1/5/1868", heb_cal: "9 Iyyar 5628", notes: "", target: "papa, joel" },
    { type: "birth", name: "Izrael Szimsia Szymon Milgram ou Milgrom", greg_date: "20/10/1871", heb_cal: "5 Cheshvan 5632", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jabijo Jacques Assa", greg_date: "28/8/1922", heb_cal: "4 Elul 5682", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jacob David 'Douvet' Milgram", greg_date: "4/1/1878", heb_cal: "29 Tevet 5638", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jacqueline Kessalis/Tchenio", greg_date: "12/11/1941", heb_cal: "22 Cheshvan 5702", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jacqueline Rouchon", greg_date: "16/12/1932", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Jacqueline Sarah Daisy Lalou-Milgram", greg_date: "26/2/1961", heb_cal: "10 Adar 5721", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jacques Tchénio", greg_date: "31/1/1967", heb_cal: "20 Sh'vat 5727", notes: "", target: "papa, joel" },
    { type: "birth", name: "jean beau-père de boris/josette", greg_date: "27/8/1942", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Jean Claude Cherki JCC", greg_date: "27/9/1943", heb_cal: "27 Elul 5703", notes: "", target: "papa" },
    { type: "birth", name: "Jean-Claude Giordano", greg_date: "24/10/1952", heb_cal: "5 Cheshvan 5713", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jeannette", greg_date: "27/9/1942", heb_cal: "16 Tishrei 5703", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jérémie Majérowicz", greg_date: "9/11/1973", heb_cal: "14 Cheshvan 5734", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jessica Neuhof", greg_date: "23/12/1988", heb_cal: "15 Tevet 5749", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jimmy Cerignano", greg_date: "23/9/1957", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jo Milgram", greg_date: "3/7/1916", heb_cal: "2 Tamuz 5676", notes: "", target: "papa, joel" },
    { type: "birth", name: "Joachim Milgram", greg_date: "8/11/2022", heb_cal: "14 Cheshvan 5783", notes: "", target: "papa, joel" },
    { type: "birth", name: "Joël Marc Marcou", greg_date: "14/8/1967", heb_cal: "8 Av 5727", notes: "", target: "papa, joel" },
    { type: "birth", name: "Johan Fils De Josette Berthe Milgram", greg_date: "15/2/1985", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Johanna Azulay", greg_date: "5/6/1974", heb_cal: "15 Sivan 5734", notes: "", target: "papa" },
    { type: "birth", name: "josée zanardi", greg_date: "28/1/1921", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Joseph Albaric", greg_date: "2/9/2011", heb_cal: "3 Elul 5771", notes: "", target: "papa, joel" },
    { type: "birth", name: "Joseph Staline", greg_date: "18/12/1878", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Josette Berthe Milgram", greg_date: "30/3/1954", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Josué Yashua Assa", greg_date: "12/1/1888", heb_cal: "28 Tevet 5648", notes: "", target: "papa, joel" },
    { type: "birth", name: "Jules Gabriel Milgram - Jaouën", greg_date: "12/12/2001", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Karl Marx", greg_date: "5/5/1818", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Keren", greg_date: "8/10/2004", heb_cal: "23 Tishrei 5765", notes: "", target: "papa, joel" },
    { type: "birth", name: "Łaja (Léa) Pasternak", greg_date: "16/12/1912", heb_cal: "6 Tevet 5673", notes: "", target: "papa, joel" },
    { type: "birth", name: "Lana Milgram", greg_date: "14/5/2013", heb_cal: "5 Sivan 5773", notes: "", target: "papa, joel" },
    { type: "birth", name: "Laurence Annick Léa", greg_date: "27/1/1953", heb_cal: "11 Sh'vat 5713", notes: "", target: "papa, joel" },
    { type: "birth", name: "Laurent Yves Yitshak", greg_date: "20/7/1962", heb_cal: "18 Tamuz 5722", notes: "", target: "papa, joel" },
    { type: "birth", name: "Lea Guila", greg_date: "2/10/1999", heb_cal: "22 Tishrei 5760", notes: "", target: "papa, joel" },
    { type: "birth", name: "Lea Rueff", greg_date: "2/5/1994", heb_cal: "21 Iyyar 5754", notes: "", target: "papa, joel" },
    { type: "birth", name: "Leib Davidovitch Fichman", greg_date: "8/7/1814", heb_cal: "20 Tamuz 5574", notes: "", target: "papa, joel" },
    { type: "birth", name: "Leïla", greg_date: "19/3/1953", heb_cal: "3 Nisan 5713", notes: "", target: "papa" },
    { type: "birth", name: "Léon Assa", greg_date: "15/10/1880", heb_cal: "10 Cheshvan 5641", notes: "", target: "papa, joel" },
    { type: "birth", name: "Léon Eliahou Minkowski", greg_date: "9/9/1935", heb_cal: "11 Elul 5695", notes: "", target: "papa, joel" },
    { type: "birth", name: "Léon Trotski", greg_date: "26/10/1879", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Léon Wachman", greg_date: "18/2/1930", heb_cal: "20 Sh'vat 5690", notes: "", target: "papa, joel" },
    { type: "birth", name: "Léonore Milgram", greg_date: "10/2/2013", heb_cal: "30 Sh'vat 5773", notes: "", target: "papa, joel" },
    { type: "birth", name: "Libi Pnina Milgram", greg_date: "1/4/2021", heb_cal: "19 Nisan 5781", notes: "", target: "papa, joel" },
    { type: "birth", name: "Lisa Milgram", greg_date: "29/8/2021", heb_cal: "21 Elul 5781", notes: "", target: "papa, joel" },
    { type: "birth", name: "Louis Claude Milgram", greg_date: "21/12/1939", heb_cal: "9 Tevet 5700", notes: "", target: "papa, joel" },
    { type: "birth", name: "Louise Milgram", greg_date: "27/12/1918", heb_cal: "24 Tevet 5679", notes: "", target: "papa, joel" },
    { type: "birth", name: "Loully Mendilevici Vainstein", greg_date: "24/7/1956", heb_cal: "16 Av 5716", notes: "", target: "papa, joel" },
    { type: "birth", name: "Luc-Yves Margueritte", greg_date: "9/5/2017", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Luca Ezekiel", greg_date: "8/4/2002", heb_cal: "26 Nisan 5762", notes: "", target: "papa, joel" },
    { type: "birth", name: "Lucie Fille De Josette M", greg_date: "9/6/1983", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Lysiane Rose", greg_date: "4/9/1939", heb_cal: "20 Elul 5699", notes: "", target: "papa, joel" },
    { type: "birth", name: "Malka Valershteiner", greg_date: "30/9/2024", heb_cal: "27 Elul 5784", notes: "", target: "papa, joel" },
    { type: "birth", name: "Marcelle Minkowski Née Kiselman", greg_date: "21/3/1926", heb_cal: "6 Nisan 5686", notes: "", target: "papa, joel" },
    { type: "birth", name: "Marie Milgram", greg_date: "12/5/1912", heb_cal: "25 Iyyar 5672", notes: "", target: "papa, joel" },
    { type: "birth", name: "Mariem Minkowska", greg_date: "26/3/1899", heb_cal: "15 Nisan 5659", notes: "Przytyk", target: "papa, joel" },
    { type: "birth", name: "Maryse Kessalis", greg_date: "20/9/1948", heb_cal: "16 Elul 5708", notes: "", target: "papa" },
    { type: "birth", name: "Mathias Majerowicz", greg_date: "3/1/1979", heb_cal: "4 Tevet 5739", notes: "", target: "papa, joel" },
    { type: "birth", name: "Mathieu Minkowski/ Fils Dalain Et Sylvie", greg_date: "7/3/1979", heb_cal: "8 Adar 5739", notes: "", target: "papa" },
    { type: "birth", name: "Maud Minkowski", greg_date: "16/5/1981", heb_cal: "12 Iyyar 5741", notes: "", target: "papa" },
    { type: "birth", name: "Maurice Moshé Moscek Minkowski", greg_date: "8/1/1925", heb_cal: "12 Tevet 5685", notes: "", target: "papa, joel" },
    { type: "birth", name: "Max Majerowicz", greg_date: "4/12/1942", heb_cal: "25 Kislev 5703", notes: "", target: "papa, joel" },
    { type: "birth", name: "Maxime Milgram", greg_date: "25/6/1989", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Meir Muny Maurice Mendelevici", greg_date: "10/12/1910", heb_cal: "9 Kislev 5671", notes: "", target: "papa, joel" },
    { type: "birth", name: "Michal (Yoh’anan/Shulamit)", greg_date: "22/12/2018", heb_cal: "14 Tevet 5779", notes: "", target: "papa, joel" },
    { type: "birth", name: "Michel Henri Milgram", greg_date: "19/9/1913", heb_cal: "17 Elul 5673", notes: "", target: "papa, joel" },
    { type: "birth", name: "Monique Rosette Majerowicz", greg_date: "31/5/1951", heb_cal: "25 Iyyar 5711", notes: "", target: "papa, joel" },
    { type: "birth", name: "Moria Tova", greg_date: "30/5/2023", heb_cal: "10 Sivan 5783", notes: "", target: "papa, joel" },
    { type: "birth", name: "Myriam Maryiem Rosenbaum", greg_date: "26/3/1895", heb_cal: "1 Nisan 5655", notes: "", target: "papa, joel" },
    { type: "birth", name: "Naama", greg_date: "12/10/2023", heb_cal: "27 Tishrei 5784", notes: "", target: "papa, joel" },
    { type: "birth", name: "Nahman Israel (Aaron/Odaya)", greg_date: "27/10/2014", heb_cal: "3 Cheshvan 5775", notes: "", target: "papa, joel" },
    { type: "birth", name: "Naomi (Avidan/Noah)", greg_date: "29/10/2015", heb_cal: "16 Cheshvan 5776", notes: "", target: "papa, joel" },
    { type: "birth", name: "Naphtali Milgram", greg_date: "28/2/2022", heb_cal: "27 Adar I 5782", notes: "", target: "papa, joel" },
    { type: "birth", name: "Nathalie Azulay", greg_date: "10/5/1976", heb_cal: "10 Iyyar 5736", notes: "", target: "papa" },
    { type: "birth", name: "Nathan Haim (Aaron/Odaya)", greg_date: "7/8/2009", heb_cal: "17 Av 5769", notes: "", target: "papa, joel" },
    { type: "birth", name: "Nicole Kessalis", greg_date: "1/1/1955", heb_cal: "7 Tevet 5715", notes: "", target: "papa" },
    { type: "birth", name: "Nina", greg_date: "20/10/2018", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Odaya (Yéhouda/Braha)", greg_date: "15/11/2014", heb_cal: "22 Cheshvan 5775", notes: "", target: "papa, joel" },
    { type: "birth", name: "Odel (Illel/Chira)", greg_date: "2/8/2017", heb_cal: "10 Av 5777", notes: "", target: "papa, joel" },
    { type: "birth", name: "Odel Lea (Aaron/Odaya)", greg_date: "13/2/2012", heb_cal: "20 Sh'vat 5772", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ouria (Avidan/Noah)", greg_date: "23/11/2013", heb_cal: "20 Kislev 5774", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ouriel David", greg_date: "5/10/2021", heb_cal: "29 Tishrei 5782", notes: "", target: "papa, joel" },
    { type: "birth", name: "Patrick Pinkhas", greg_date: "17/1/1949", heb_cal: "16 Tevet 5709", notes: "", target: "papa, joel" },
    { type: "birth", name: "Paul Sussman", greg_date: "11/7/1943", heb_cal: "8 Tamuz 5703", notes: "", target: "papa" },
    { type: "birth", name: "Paulette Grymann", greg_date: "2/2/1932", heb_cal: "25 Sh'vat 5692", notes: "", target: "papa, joel" },
    { type: "birth", name: "Philippe Albaric", greg_date: "25/1/1963", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Pierre Cerignano", greg_date: "21/9/2003", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Pierre Seignol", greg_date: "9/2/1949", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Pierrette", greg_date: "27/9/1942", heb_cal: "16 Tishrei 5703", notes: "", target: "papa, joel" },
    { type: "birth", name: "Pinia Pinhas Yutsis", greg_date: "5/7/1905", heb_cal: "2 Tamuz 5665", notes: "", target: "papa, joel" },
    { type: "birth", name: "Primo Levi", greg_date: "31/1/1919", heb_cal: "30 Sh'vat 5679", notes: "", target: "papa" },
    { type: "birth", name: "Rachel Guez", greg_date: "1/4/1979", heb_cal: "4 Nisan 5739", notes: "", target: "papa, joel" },
    { type: "birth", name: "Rahel Simhah", greg_date: "21/10/1989", heb_cal: "22 Tishrei 5750", notes: "", target: "papa, joel" },
    { type: "birth", name: "Raphaël Feigelson", greg_date: "17/2/1926", heb_cal: "3 Adar 5686", notes: "", target: "papa, joel" },
    { type: "birth", name: "Rebeca Adout", greg_date: "28/3/1943", heb_cal: "21 Adar II 5703", notes: "", target: "papa, joel" },
    { type: "birth", name: "Reh'avieh Minkowski", greg_date: "19/5/1925", heb_cal: "25 Iyyar 5685", notes: "", target: "papa, joel" },
    { type: "birth", name: "Renaud David", greg_date: "13/2/1965", heb_cal: "11 Adar I 5725", notes: "un Shabbèss", target: "papa, joel" },
    { type: "birth", name: "René Daniel Lévy", greg_date: "13/2/1942", heb_cal: "26 Sh'vat 5702", notes: "", target: "papa, joel" },
    { type: "birth", name: "robert sivilia", greg_date: "19/4/1941", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Roberto Assa", greg_date: "14/10/1943", heb_cal: "15 Tishrei 5704", notes: "", target: "papa, joel" },
    { type: "birth", name: "Rosa Alfandery Assa", greg_date: "12/4/1889", heb_cal: "11 Nisan 5649", notes: "", target: "papa, joel" },
    { type: "birth", name: "Rosa Mendilevitch", greg_date: "24/3/1987", heb_cal: "23 Adar 5747", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ruben Almir Tanguy Albaric", greg_date: "20/7/2001", heb_cal: "29 Tamuz 5761", notes: "", target: "papa, joel" },
    { type: "birth", name: "Rudy Minkowski", greg_date: "12/4/1980", heb_cal: "26 Nisan 5740", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ruth (Efraïm/Léa)", greg_date: "16/9/2020", heb_cal: "27 Elul 5780", notes: "", target: "papa, joel" },
    { type: "birth", name: "Samuel Frère de Papa", greg_date: "1/3/1902", heb_cal: "22 Adar I 5662", notes: "Assassiné à AUSCHWITZ", target: "papa, joel" },
    { type: "birth", name: "Samuel Zénon (Yoda) Milgram", greg_date: "27/1/1983", heb_cal: "13 Sh'vat 5743", notes: "", target: "papa, joel" },
    { type: "birth", name: "Sarah Hélène Tchénio/Korsia", greg_date: "10/11/1973", heb_cal: "15 Cheshvan 5734", notes: "", target: "papa" },
    { type: "birth", name: "Sarah Milgram", greg_date: "26/10/1979", heb_cal: "5 Cheshvan 5740", notes: "", target: "papa, joel" },
    { type: "birth", name: "Sarah Talerman", greg_date: "18/11/1924", heb_cal: "21 Cheshvan 5685", notes: "", target: "papa, joel" },
    { type: "birth", name: "Schmouel Milgram", greg_date: "31/5/2012", heb_cal: "10 Sivan 5772", notes: "(Yéhouda/Braha)", target: "papa, joel" },
    { type: "birth", name: "Serge Cerignano", greg_date: "2/3/1956", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Shimon Milgram", greg_date: "12/3/2003", heb_cal: "8 Adar II 5763", notes: "", target: "papa, joel" },
    { type: "birth", name: "Shimon Milgrom", greg_date: "24/11/2022", heb_cal: "30 Cheshvan 5783", notes: "", target: "papa, joel" },
    { type: "birth", name: "Shimon Milgrom", greg_date: "1/1/2024", heb_cal: "20 Tevet 5784", notes: "", target: "papa, joel" },
    { type: "birth", name: "Sounia Sukhar Yutsis", greg_date: "16/2/2012", heb_cal: "23 Sh'vat 5772", notes: "", target: "papa, joel" },
    { type: "birth", name: "Stéphane Falivène", greg_date: "12/9/1969", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Suzy Sarah Minkowska/Chiche/Vadbled", greg_date: "8/1/1925", heb_cal: "12 Tevet 5685", notes: "", target: "papa, joel" },
    { type: "birth", name: "Sylvia Spira Majerowicz", greg_date: "5/6/1951", heb_cal: "1 Sivan 5711", notes: "", target: "papa, joel" },
    { type: "birth", name: "Sylvie Minkowski", greg_date: "3/5/1955", heb_cal: "11 Iyyar 5715", notes: "", target: "papa" },
    { type: "birth", name: "Szmul Uszer Salomon Milgram", greg_date: "28/9/1942", heb_cal: "17 Tishrei 5703", notes: "", target: "papa, joel" },
    { type: "birth", name: "Tael (Illel/Chira)", greg_date: "15/8/2018", heb_cal: "4 Elul 5778", notes: "", target: "papa, joel" },
    { type: "birth", name: "Tamar (Efraïm/Léa)", greg_date: "20/6/2017", heb_cal: "26 Sivan 5777", notes: "", target: "papa, joel" },
    { type: "birth", name: "Thierry Minkowski", greg_date: "8/11/1964", heb_cal: "3 Kislev 5725", notes: "", target: "papa, joel" },
    { type: "birth", name: "Thomas Benjamin Milgram", greg_date: "3/8/1971", heb_cal: "12 Av 5731", notes: "", target: "papa, joel" },
    { type: "birth", name: "Tzipora Milgram", greg_date: "14/3/2021", heb_cal: "1 Nisan 5781", notes: "", target: "papa, joel" },
    { type: "birth", name: "Ulysse Simon Abraham Sistonako Matitia", greg_date: "3/8/2006", heb_cal: "9 Av 5766", notes: "", target: "papa, joel" },
    { type: "birth", name: "Varda Ninon Levy", greg_date: "13/10/1975", heb_cal: "8 Cheshvan 5736", notes: "", target: "papa, joel" },
    { type: "birth", name: "Victoria (Viviane) Lipskier", greg_date: "5/6/1971", heb_cal: "12 Sivan 5731", notes: "", target: "papa" },
    { type: "birth", name: "Violette Simonne (Zimbul)", greg_date: "19/10/1916", heb_cal: "22 Tishrei 5677", notes: "", target: "papa, joel" },
    { type: "birth", name: "Vladimir Ilitch Oulianov, dit Lénine", greg_date: "22/4/1870", heb_cal: "", notes: "", target: "papa" },
    { type: "birth", name: "Yaakov Yossef (Rah’el/Simh'a)", greg_date: "10/4/2018", heb_cal: "25 Nisan 5778", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yachoua Assa (Menachem/Bea)", greg_date: "12/1/1888", heb_cal: "28 Tevet 5648", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yann Majerowicz", greg_date: "12/1/1976", heb_cal: "10 Sh'vat 5736", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yedidia (Avidan/Noah)", greg_date: "24/10/2010", heb_cal: "16 Cheshvan 5771", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yehonathan (Avidan/Noah)", greg_date: "1/4/2009", heb_cal: "7 Nisan 5769", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yehouda Milgram/Milgrom MICHPATIMË", greg_date: "27/2/1987", heb_cal: "28 Sh'vat 5747", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yeoudit Nazma (Adina/Raphaël)", greg_date: "22/8/2020", heb_cal: "2 Elul 5780", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yoh'anan Meir Milgram", greg_date: "7/12/1990", heb_cal: "20 Kislev 5751", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yonathan (Yéhouda/Braha)", greg_date: "2/10/2013", heb_cal: "28 Tishrei 5774", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yonathânë", greg_date: "30/5/1996", heb_cal: "12 Sivan 5756", notes: "", target: "papa" },
    { type: "birth", name: "Yossef (Aaron/Odaya)", greg_date: "11/2/2017", heb_cal: "15 Sh'vat 5777", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yska (Hanna/Yossef)", greg_date: "25/11/2017", heb_cal: "7 Kislev 5778", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yves Paul Margueritte", greg_date: "15/1/2009", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "birth", name: "Yvette Chawa Minkowska", greg_date: "12/9/1926", heb_cal: "4 Tishrei 5687", notes: "", target: "papa, joel" },
    { type: "death", name: "Abraham Minkowski", greg_date: "3/8/1942", heb_cal: "20 Av 5702", notes: "", target: "papa, joel" },
    { type: "death", name: "Abram Albert Mendilevitch", greg_date: "10/1/2004", heb_cal: "16 Tevet 5764", notes: "", target: "papa, joel" },
    { type: "death", name: "Abram Berek Grosberg", greg_date: "11/9/1877", heb_cal: "4 Tishrei 5638", notes: "", target: "papa, joel" },
    { type: "death", name: "Alain Henri Minkowski", greg_date: "7/8/2009", heb_cal: "17 Av 5769", notes: "", target: "papa, joel" },
    { type: "death", name: "Albert Einstein", greg_date: "18/4/1955", heb_cal: "26 Nisan 5715", notes: "", target: "papa" },
    { type: "death", name: "Albert Kessalis", greg_date: "30/6/1994", heb_cal: "21 Tamuz 5754", notes: "", target: "papa" },
    { type: "death", name: "Annie Henriette Francoise Seignol", greg_date: "21/12/2018", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "death", name: "Bela Mendilevici", greg_date: "10/5/2007", heb_cal: "22 Iyyar 5767", notes: "", target: "papa, joel" },
    { type: "death", name: "Berthe Brandla Billy Minkowska", greg_date: "24/9/2000", heb_cal: "24 Elul 5760", notes: "", target: "papa, joel" },
    { type: "death", name: "Berthe Rose Assa", greg_date: "12/11/1911", heb_cal: "21 Cheshvan 5672", notes: "", target: "papa, joel" },
    { type: "death", name: "Berthe Victoire Assa", greg_date: "23/1/2004", heb_cal: "29 Tevet 5764", notes: "", target: "papa, joel" },
    { type: "death", name: "Berthe Zelda Milgram", greg_date: "23/9/1942", heb_cal: "12 Tishrei 5703", notes: "", target: "papa, joel" },
    { type: "death", name: "Daniel Milgram", greg_date: "6/11/2017", heb_cal: "17 Cheshvan 5778", notes: "", target: "papa, joel" },
    { type: "death", name: "Eleazar Lazare Assa", greg_date: "14/10/1943", heb_cal: "15 Tishrei 5704", notes: "", target: "papa, joel" },
    { type: "death", name: "Elianne Sultana Chiche", greg_date: "4/6/2020", heb_cal: "12 Sivan 5780", notes: "", target: "papa, joel" },
    { type: "death", name: "Francis Noé Assa", greg_date: "13/8/1983", heb_cal: "4 Elul 5743", notes: "", target: "papa, joel" },
    { type: "death", name: "Gilbert Robert Mizrahi", greg_date: "29/8/1935", heb_cal: "30 Av 5695", notes: "", target: "papa, joel" },
    { type: "death", name: "Harry Schartenberg", greg_date: "30/8/1947", heb_cal: "14 Elul 5707", notes: "", target: "papa, joel" },
    { type: "death", name: "Henri Majerowicz", greg_date: "6/6/1992", heb_cal: "5 Sivan 5752", notes: "", target: "papa, joel" },
    { type: "death", name: "Hermann Minkowski", greg_date: "12/12/1921", heb_cal: "11 Kislev 5682", notes: "", target: "papa, joel" },
    { type: "death", name: "Houmalè", greg_date: "4/5/1960", heb_cal: "7 Iyyar 5720", notes: "", target: "papa, joel" },
    { type: "death", name: "Jabijo Jacques Assa", greg_date: "14/10/1943", heb_cal: "15 Tishrei 5704", notes: "", target: "papa, joel" },
    { type: "death", name: "Jacob David 'Douvet' Milgram", greg_date: "9/2/1940", heb_cal: "30 Sh'vat 5700", notes: "", target: "papa, joel" },
    { type: "death", name: "Jimmy Cerignano", greg_date: "29/6/1979", heb_cal: "", notes: "", target: "papa" },
    { type: "death", name: "Jo Milgram", greg_date: "7/11/2005", heb_cal: "5 Cheshvan 5766", notes: "", target: "papa, joel" },
    { type: "death", name: "Joseph Staline", greg_date: "5/3/1953", heb_cal: "", notes: "", target: "papa" },
    { type: "death", name: "Josué Yashua Assa", greg_date: "23/12/1952", heb_cal: "5 Tevet 5713", notes: "", target: "papa, joel" },
    { type: "death", name: "Karl Marx", greg_date: "14/3/1883", heb_cal: "", notes: "", target: "papa" },
    { type: "death", name: "Laurence Annick Léa", greg_date: "1/10/2012", heb_cal: "15 Tishrei 5773", notes: "", target: "papa, joel" },
    { type: "death", name: "Leïla", greg_date: "2/7/2007", heb_cal: "16 Tamuz 5767", notes: "", target: "papa" },
    { type: "death", name: "Léon Assa", greg_date: "28/3/1943", heb_cal: "21 Adar II 5703", notes: "", target: "papa, joel" },
    { type: "death", name: "Léon Trotski", greg_date: "21/8/1940", heb_cal: "", notes: "Assassiné à Mexico", target: "papa" },
    { type: "death", name: "Léon Wachman", greg_date: "24/12/2015", heb_cal: "12 Tevet 5776", notes: "", target: "papa, joel" },
    { type: "death", name: "Louise Milgram", greg_date: "11/4/1919", heb_cal: "11 Nisan 5679", notes: "", target: "papa, joel" },
    { type: "death", name: "Luc-Yves Margueritte", greg_date: "17/11/1948", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "death", name: "Marcelle Myriam Kiselman", greg_date: "31/10/2016", heb_cal: "29 Tishrei 5777", notes: "", target: "papa, joel" },
    { type: "death", name: "Marie Milgram", greg_date: "21/2/1913", heb_cal: "14 Adar I 5673", notes: "", target: "papa, joel" },
    { type: "death", name: "Mariem Minkowska", greg_date: "30/11/1976", heb_cal: "8 Kislev 5737", notes: "", target: "papa, joel" },
    { type: "death", name: "Maurice Moshé Moscek Minkowski", greg_date: "13/12/2020", heb_cal: "28 Kislev 5781", notes: "", target: "papa, joel" },
    { type: "death", name: "Meir Muny Maurice Mendelevici", greg_date: "18/4/1998", heb_cal: "22 Nisan 5758", notes: "", target: "papa, joel" },
    { type: "death", name: "Michel Henri Milgram", greg_date: "27/12/2005", heb_cal: "26 Kislev 5766", notes: "", target: "papa, joel" },
    { type: "death", name: "Petit Charles (Bénita)", greg_date: "7/5/1992", heb_cal: "4 Iyyar 5752", notes: "", target: "papa" },
    { type: "death", name: "Pierre Cerignano", greg_date: "13/10/1932", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "death", name: "Primo Levi", greg_date: "11/4/1987", heb_cal: "12 Nisan 5747", notes: "Suicide", target: "papa" },
    { type: "death", name: "Raphaël Feigelson", greg_date: "1/4/2021", heb_cal: "19 Nisan 5781", notes: "", target: "papa, joel" },
    { type: "death", name: "René Daniel Levy", greg_date: "5/3/2021", heb_cal: "21 Adar 5781", notes: "", target: "papa, joel" },
    { type: "death", name: "Rosa Alfandery Assa", greg_date: "16/4/1960", heb_cal: "19 Nisan 5720", notes: "", target: "papa, joel" },
    { type: "death", name: "Sounia Sukhar Yutsis", greg_date: "17/12/1933", heb_cal: "29 Kislev 5694", notes: "", target: "papa, joel" },
    { type: "death", name: "Suzy Sarah Minkowska", greg_date: "19/2/2022", heb_cal: "18 Adar I 5782", notes: "", target: "papa, joel" },
    { type: "death", name: "Szmul Uszer Salomon Milgram", greg_date: "1/3/1902", heb_cal: "22 Adar I 5662", notes: "", target: "papa, joel" },
    { type: "death", name: "Violette Simonne (Zimbul)", greg_date: "1/12/1982", heb_cal: "15 Kislev 5743", notes: "", target: "papa, joel" },
    { type: "death", name: "Vladimir Ilitch Oulianov, dit Lénine", greg_date: "21/1/1924", heb_cal: "", notes: "", target: "papa" },
    { type: "death", name: "Yves Paul Margueritte", greg_date: "19/8/1912", heb_cal: "", notes: "", target: "papa, joel" },
    { type: "death", name: "Yvette Chawa Minkowska", greg_date: "20/9/2000", heb_cal: "20 Elul 5760", notes: "", target: "papa, joel" },
    { type: "event", name: "Assassinat Yitzhakh Rabin", greg_date: "4/11/1995", heb_cal: "11 Cheshvan 5756", notes: "", target: "papa" },
    { type: "event", name: "association à but non lucratif", greg_date: "1/7/1901", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "aurore/j'accuse/emile zola", greg_date: "13/1/1898", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "austerlitz/moravie", greg_date: "2/12/1805", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "débarquement en normandie", greg_date: "6/6/1944", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "décret napoléonien indigne", greg_date: "17/3/1808", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "décret relatif aux travaux de génie civil BTP", greg_date: "8/1/1964", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "Entrée Solaris/Vega", greg_date: "29/1/2008", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "fin état guerre jordanie/israel", greg_date: "26/7/1994", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "Guerre des 6 Jours", greg_date: "6/6/1967", heb_cal: "27 Iyyar 5727", notes: "", target: "papa" },
    { type: "event", name: "insurrection ghetto varsovie", greg_date: "19/4/1943", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "naissance REPUBLIQUE INDIENNE/PAKISTAN", greg_date: "15/5/1948", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "paix égypte/israël/ carter-el saadate-begin", greg_date: "26/3/1979", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "Phare de l'Etang GLDF 612", greg_date: "8/2/1970", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "schabbèss d'acquisition de BETéÏNOU/Dr GRENIER", greg_date: "21/2/1970", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "Taba suite/new york/arafat/rabin", greg_date: "28/9/1995", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "tchernobyl réacteur 4 (ukraine)", greg_date: "26/4/1986", heb_cal: "", notes: "", target: "papa" },
    { type: "event", name: "washington/taba/clinton/rabin/arafat", greg_date: "13/9/1993", heb_cal: "", notes: "", target: "papa" },
    { type: "wedding", name: "Adina et Raphael Yehouda Elkaïm", greg_date: "11/9/2019", heb_cal: "11 Elul 5779", notes: "", target: "papa, joel" },
    { type: "wedding", name: "Aharon/Odeïya", greg_date: "25/3/2008", heb_cal: "18 Adar II 5768", notes: "Tenoïm", target: "papa, joel" },
    { type: "wedding", name: "Albert Violette", greg_date: "10/4/1938", heb_cal: "9 Nisan 5698", notes: "synagogue SALZER", target: "papa, joel" },
    { type: "wedding", name: "Avidan/Noah", greg_date: "4/11/2006", heb_cal: "13 Cheshvan 5767", notes: "Wort", target: "papa, joel" },
    { type: "wedding", name: "Avidan/Noah", greg_date: "7/11/2006", heb_cal: "16 Cheshvan 5767", notes: "Tenoïm", target: "papa, joel" },
    { type: "wedding", name: "Berthe/Michel", greg_date: "28/11/1937", heb_cal: "24 Kislev 5698", notes: "", target: "papa, joel" },
    { type: "wedding", name: "daniel/jeannette", greg_date: "5/9/1968", heb_cal: "", notes: "mairie", target: "papa, joel" },
    { type: "wedding", name: "Daniel/Jeannette", greg_date: "8/9/1968", heb_cal: "15 Elul 5728", notes: "", target: "papa, joel" },
    { type: "wedding", name: "Ety/Henri", greg_date: "15/12/1946", heb_cal: "22 Kislev 5707", notes: "", target: "papa, joel" },
    { type: "wedding", name: "Laurent/Jacqueline", greg_date: "9/9/1984", heb_cal: "12 Elul 5744", notes: "", target: "papa, joel" },
    { type: "wedding", name: "Lysiane/Claude", greg_date: "10/10/1961", heb_cal: "30 Tishrei 5722", notes: "", target: "papa, joel" },
    { type: "wedding", name: "Tenoïm Berthe/Michel", greg_date: "10/5/1936", heb_cal: "18 Iyyar 5696", notes: "", target: "papa, joel" },
    { type: "wedding", name: "Yachoua/Rosa Assa", greg_date: "11/8/1910", heb_cal: "6 Av 5670", notes: "", target: "papa, joel" },
];
export default anniversaires;